### PR TITLE
only send protocol header if protocol supplied

### PR DESCRIPTION
**Pull request by willmcgugan**
**What this PR solves**

- Avoids sending an empty websocket protocol header. aiohttp log a warning if it is empty.

**How it is done**

- Simple conditional statement.

**What to look out for**

- logic errors.

**Review**

- [X] Ready for review

### CODE REVIEW

**Comment by willmcgugan** [comment]
@wildfoundry/web-developers easy one I promise

**Comment by meshy** [comment]
Oops, I should have spotted that!

**Comment by willmcgugan** [comment]
Hang your head in shame @meshy

**Pull request merged**
